pip install flask==0.9
pip install flask-login
pip install flask-openid
pip install flask-mail==0.7.6
pip install sqlalchemy==0.7.9
pip install flask-sqlalchemy==0.16
pip install sqlalchemy-migrate==0.7.2
pip install flask-whooshalchemy==0.54a
pip install flask-wtf==0.8.4
pip install pytz==2013b
pip install flask-babel==0.8
pip install flup
